# Generated by Django 4.2.1 on 2023-06-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleaccountimages',
            old_name='article',
            new_name='account',
        ),
    ]
