# Generated by Django 4.2.1 on 2023-06-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reviews',
        ),
    ]
