# Generated by Django 4.2.1 on 2023-06-02 16:12

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_multipleimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimages',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='multipleimages',
            name='image',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=articles.models.generate_filename),
        ),
    ]
