# Generated by Django 4.2.1 on 2023-06-08 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_review_article'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('article', 'owner')},
        ),
    ]
