# Generated by Django 4.2.1 on 2023-06-08 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleBlogImages',
            fields=[
                ('image', models.FileField(blank=True, null=True, unique=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogadmin.bloginfo')),
            ],
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='footer_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer', to='blogadmin.multipleblogimages'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='navigation_bar_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar', to='blogadmin.multipleblogimages'),
        ),
    ]
